services:
  postgres:
    image: postgres:17
    container_name: stockflow-postgres

    environment:
      POSTGRES_DB: stockflow
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data



  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: stockflow-api
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/stockflow
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin


volumes:
  postgres_data: